services:
  postgres:
    image: postgres:18-alpine
    container_name: myspringboot-postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: kaiser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql   # DOÄžRU YOL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kaiser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
